export default {
    // 主题
    THEME_CHANGE:"THEME_CHANGE",
    THEME_INIT:"THEME_INIT",

    // 最热
    POPULAR_REFRESH:"POPULAR_REFRESH",
    POPULAR_LOAD_FAIL:"POPULAR_LOAD_FAIL",
    POPULAR_LOAD_SUCCESS:'POPULAR_LOAD_SUCCESS',

    POPULAR_LOAD_MORE:"POPULAR_LOAD_MORE",
    POPULAR_LOAD_MORE_FAIL:"POPULAR_LOAD_MORE_FAIL",
    POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',



    // 趋势
    TRENDING_REFRESH:"TRENDING_REFRESH",
    TRENDING_LOAD_FAIL:"TRENDING_LOAD_FAIL",
    TRENDING_LOAD_SUCCESS:'TRENDING_LOAD_SUCCESS',

    TRENDING_LOAD_MORE:"TRENDING_LOAD_MORE",
    TRENDING_LOAD_MORE_FAIL:"TRENDING_LOAD_MORE_FAIL",
    TRENDING_LOAD_MORE_SUCCESS:'TRENDING_LOAD_MORE_SUCCESS',

    // 收藏
    FAV_REFRESH:"FAV_REFRESH",
    FAV_LOAD_FAIL:"FAV_LOAD_FAIL",
    FAV_LOAD_SUCCESS:'FAV_LOAD_SUCCESS',

    // 语言
    LANGUAGE_LOAD_SUCCESS:"LANGUAGE_LOAD_SUCCESS"
}