export default {
    THEME_CHANGE:"THEME_CHANGE",
    THEME_INIT:"THEME_INIT",

    POPULAR_REFRESH:"POPULAR_REFRESH",
    POPULAR_LOAD_FAIL:"POPULAR_LOAD_FAIL",
    POPULAR_LOAD_SUCCESS:'POPULAR_LOAD_SUCCESS',

    POPULAR_LOAD_MORE:"POPULAR_LOAD_MORE",
    POPULAR_LOAD_MORE_FAIL:"POPULAR_LOAD_MORE_FAIL",
    POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS'

}